/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'FIBONACCI' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"

/* Keil::CMSIS Driver:CAN@1.10 */
#define RTE_Drivers_CAN1                /* Driver CAN1 */
#define RTE_Drivers_CAN2                /* Driver CAN2 */


#endif /* RTE_COMPONENTS_H */
